Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -9,11 +9,12 @@ jobs:
   publish:
     runs-on: ubuntu-latest
     env:
-      FORK: 'dive2Pro'
+      FORK: '${{ github.repository_owner }}'
       USER: 'dive2Pro'
       EMAIL: 'toylucklebo@gmail.com'
-      BRANCH: 'Native-Dark'
-      EXTENSION_JSON: 'extensions/hyc/roam-native-dark.json'
+      BRANCH: ''
+      EXTENSION_DIR: 'extensions/...'
+      EXTENSION_JSON: 'extensions/....json'
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
@@ -35,23 +36,32 @@ jobs:
           git checkout -B main upstream/main
           git push -f origin main
 
-      - name: Delete ${{ env.BRANCH }} branch if exists
-        run: |
-          git push origin -d ${{env.BRANCH}} || true
-          
       - name: Create ${{env.BRANCH}} branch from main
         run: |
           git checkout -b ${{env.BRANCH}} origin/main
 
-      - name: Update $EXTENSION_JSON
+      - name: Update $EXTENSION_DIR
         run: |
-          sed -i 's/"source_commit": ".*/"source_commit": "'"$GITHUB_SHA"'",/g' $EXTENSION_JSON
+          mkdir ${{ env.EXTENSION_DIR }} || true
+          cat <<EOF > ${{ env.EXTENSION_JSON }}
+              {
+                "name": "",
+                "short_description": "",
+                "author": "",
+                "source_url": "${{github.server_url}}/${{ github.repository }}",
+                "source_repo": "${{github.server_url}}/${{ github.repository }}.git",
+                "source_commit": "$GITHUB_SHA",
+                "stripe_account": ""
+              }            
+          EOF
 
       - name: Commit and Push changes
         run: |
+          git pull
           git add ${{ env.EXTENSION_JSON }}
           git commit -m "Update source_commit to $GITHUB_SHA"
-          git push -u origin ${{ env.BRANCH }}
+          git push --force origin ${{ env.BRANCH }}
+          
       - name: Create pull request
         uses: actions/github-script@v4
         with:
@@ -60,16 +70,20 @@ jobs:
             const branch = "${{ env.BRANCH }}"; // Replace with the branch you want to create a PR for
             const owner = 'Roam-Research';
             const repo = 'roam-depot';
-            const title = 'Update ${{ env.BRANCH }}';
+            const title = '${{ env.BRANCH }}';
             const body = '';
             const head = '${{env.FORK}}:${{env.BRANCH}}';
-            const base = 'main'; // Replace with the branch you want to merge the PR into
-            const { data: pullRequest } = await github.pulls.create({
-              owner,
-              repo,
-              title,
-              body,
-              head,
-              base,
-            });
-            console.log(`PR created: ${pullRequest.html_url}`);
+            const base = 'main'; // Replace with the branch you want to merge the PR into 
+            try {
+              const { data: pullRequest } = await github.pulls.create({
+                owner,
+                repo,
+                title,
+                body,
+                head,
+                base,
+              });
+              console.log(`PR created: ${pullRequest.html_url}`);
+            } catch(e) {
+              console.log('PR creating failed', e);
+            }
